config/routes.rb
Memworks::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :users do
    resources :enrollments, only: [:create]
    resources :courseworks, only: [:create, :update]
    resources :cards, controller: :user_cards, only: [:index]
    resource  :my_deck, only: [:show]
  end

  resources :lessons, only: [:index, :show] do
    resources :assignments, only: [:show]
    resources :challenges, only: [:show]
  end

  resources :challenges, only: [:index] do
    resources :challenge_completions, only: [:create]
    resources :cards, controller: :challenge_cards, only: [:index]
  end

  resources :cards, only: [] do
    resources :card_submission_logs, only: [:create]
  end

  resource :dashboard, only: [:show]

  root to: 'main_pages#home'

  match '/about' => 'main_pages#about'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many  :activities,
            inverse_of: :lesson,
            dependent: :destroy
  has_many  :enrollments,
            inverse_of: :lesson,
            dependent: :destroy
  has_many  :courseworks,
            inverse_of: :lesson,
            dependent: :destroy
  has_many  :users,
            through: :enrollments,
            inverse_of: :lessons

  validates_presence_of :title, :summary

  attr_accessible :summary, :title

  class << self
    def ascending_by_title
      order("title ASC")
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  inherit_resources
  actions :index, :show

  def index
    index! do
      @enrollment = Enrollment.new
    end
  end

  def show
    show! do
      @coursework = Coursework.new
    end
  end

end

app/views/lessons/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="breadcrumbs">
      <li><%= link_to("Home", root_path) %></li>
      <li class="current"><%= link_to("Lessons", lessons_path) %></li>
    </ul>
  </div>
</div>
<ul class="lesson-list">
  <%- @lessons.ascending_by_title.each do |lesson| -%>
    <div class="row">
      <li class="large-12 columns panel lesson-entry">
          <div class="large-8 columns">
            <div class="lesson-title"><h4><%= lesson.title %></h4></div>
            <div class="lesson-summary"><h4 class="subheader"><%= lesson.summary %></h4></div>
          </div>
          <div class="large-4 columns">
            <%- if user_signed_in? -%>
              <%- if current_user.lessons.include?(lesson) -%>
                <%- if current_user.lesson_completed?(lesson) -%>
                  <%= button_to("Review", lesson_path(lesson), class: "large button secondary", method: "get") %>
                <%- else -%>
                  <%= button_to("Continue", lesson_path(lesson), class: "large button", method: "get") %>
                <%- end -%>
              <%- else -%>
                <%= simple_form_for([current_user, @enrollment]) do |f| %>
                  <%= f.hidden_field :lesson_id, value: lesson.id %>
                  <%= f.submit "Start", class: "large button success" %>
                <%- end -%>
              <%- end -%>
            <%- else -%>
              <%= button_to("Start", lesson_path(lesson), class: "large button success", method: "get") %>
            <%- end -%>
          </div>
      </li>
    </div>
  <%- end -%>
  <div class="row">
    <li class="large-12 columns panel lesson-entry">
      <h5>More lessons coming soon!</h5>
    </li>
  </div>
</ul>

app/views/lessons/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="breadcrumbs">
      <li><%= link_to("Home", root_path) %></li>
      <li><%= link_to("Lessons", lessons_path) %></li>
      <li class="current"><%= link_to(@lesson.title, lesson_path(@lesson)) %></li>
    </ul>
  </div>
<h2><%= @lesson.title %></h2>
<%- @lesson.activities.descending_position.each do |activity| -%>
  <div class="row">
    <%- if activity.completable_type == "Assignment" -%>
      <%- assignment = activity.completable -%>
      <div class="large-12 columns assignment panel">
        <div class="large-8 columns">
          <span class="label">Assignment</span><h5 class="assignment-title"><%= "#{activity.completable.title} " %></h5>
          <h5 class="subheader"><%= assignment.summary %></h5>
        </div>
        <div class="large-3 columns">
          <%- if user_signed_in? -%>
            <%- if current_user.assignments.include?(assignment) -%>
              <%- coursework = current_user.assignment_progress(assignment) -%>
              <%- if coursework.completed? %> 
                <%= button_to("Repeat", lesson_assignment_path(@lesson, assignment), class: "button completable-start secondary", method: "get") %>
                <small><%= "Completed in #{coursework.lesson.title}" unless coursework.lesson == @lesson %></small>
              <%- else -%>
                <%= button_to("Continue", lesson_assignment_path(@lesson, assignment), class: "button completable-start", method: "get") %>
              <%- end -%>
            <%- else -%>
              <%= simple_form_for([current_user, @coursework]) do |f| %>
                <%= f.hidden_field :assignment_id, value: assignment.id %>
                <%= f.hidden_field :lesson_id, value: @lesson.id %>
                <%= f.submit "Start", class: "button completable-start success" %>
              <%- end -%>
            <%- end -%>
          <%- else -%>
            <%= button_to("Start", lesson_assignment_path(@lesson, assignment), class: "button completable-start success", method: "get") %>
          <%- end -%>
        </div>
      </div>
    <%- elsif activity.completable_type == "Challenge" -%>
      <%- challenge = activity.completable -%>
      <div class="large-12 columns challenge panel">
        <div class="large-8 columns">
          <span class="label">Challenge</span><h5 class="challenge-title"><%= "#{challenge.title} " %></h5>
        </div>
        <div class="large-3 columns">
          <%- if user_signed_in? -%>
            <%- if current_user.challenges.include?(challenge) -%>
              <%= link_to("Replay", lesson_challenge_path(@lesson, challenge), class: "button completable-start secondary") %>
            <%- else -%>
              <%= link_to("Start", lesson_challenge_path(@lesson, challenge), class: "button completable-start success") %>
            <%- end -%>
          <%- else -%>
            <%= link_to("Start", lesson_challenge_path(@lesson, challenge), class: "button completable-start success") %>
          <%- end -%>
        </div>
      </div>
    <%- end -%>
  </div>
<%- end -%>