config/routes.rb
Memworks::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :users do
    resources :enrollments, only: [:create]
    resources :courseworks, only: [:create, :update]
    resources :cards, controller: :user_cards, only: [:index]
    resource  :my_deck, only: [:show]
  end

  resources :lessons, only: [:index, :show] do
    resources :assignments, only: [:show]
    resources :challenges, only: [:show]
  end

  resources :challenges, only: [:index] do
    resources :challenge_completions, only: [:create]
    resources :cards, controller: :challenge_cards, only: [:index]
  end

  resources :cards, only: [] do
    resources :card_submission_logs, only: [:create]
  end

  resource :dashboard, only: [:show]

  root to: 'main_pages#home'

  match '/about' => 'main_pages#about'

end

app/views/layouts/_big_header.html.erb
<div class="masthead">
  <h1 class="logo"><%= link_to("Memworks ", root_path) %></h1><h2 class="logo subheader">Boosted Learning</h2>
  <%- if user_signed_in? -%>
    <%= link_to("Get Started", lessons_path, :class =>"button success get-started") %>
  <%- else -%>
    <%= link_to("Get Started", new_user_registration_path, :class =>"button success get-started") %>
  <%- end -%>
</div>
<div class="panel callout" id="main-banner">
  <div class="row">
    <div class="large-4 columns">
      <h4>Learn Faster</h4>
    </div>
    <div class="large-4 columns">
      <h4>Retain Longer</h4>
    </div>
    <div class="large-4 columns">
      <h4>Track Your Progress</h4>
    </div>
  </div>
</div>

app/views/layouts/_small_header.html.erb
<div class="masthead">
  <h3 class="logo"><%= link_to("Memworks ", root_path) %></h3><h3 class="logo subheader">Boosted Learning</h3>
</div>

app/views/layouts/_top_navigation.html.erb
  <div class="contain-to-grid sticky">
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to("",root_path) %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <%- if user_signed_in? -%>
            <li class="divider"></li>
            <%- if current_user.has_cards? -%>
              <li><%= link_to("Practice", user_my_deck_path(current_user), id: "practice-call") %></li>
            <%- else -%>
              <li><%= link_to("Practice", user_my_deck_path(current_user)) %></li>
            <%- end -%>
          <%- end -%>
          <li class="divider"></li>
          <li><%= link_to("Explore Lessons", lessons_path) %></li>
          <li class="divider"></li>
        </ul>
        <ul class="right">
          <li class="divider"></li>
          <%- if user_signed_in? -%>
            <li><%= link_to("Dashboard", dashboard_path) %></li>
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#"><%= current_user.email %></a>
              <ul class="dropdown">
                <li><label>My Account</label></li>
                <li><%= link_to("Manage Account", edit_user_registration_path) %></li>
                <%- if can? :manage, :all -%>
                  <li><%= link_to("Superadmin", rails_admin_path) %></li>
                <%- end -%>
                <li><%= link_to("Sign Out", destroy_user_session_path, method: 'delete') %></li>
              </ul>
            </li>
          <%- else -%>
            <li><%= link_to("Sign In", new_user_session_path) %></li>
            <li class="divider"></li>
            <li><%= link_to("Sign Up", new_user_registration_path) %></li>
          <%- end -%>
          <li class="divider"></li>
        </ul>
      </section>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Memworks" %></title>
    
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= @big_header ? render('layouts/big_header') : render('layouts/small_header') %>
    <%= render 'layouts/top_navigation' %>

    <%- if flash[:error] -%>
      <div class="row">
        <div class="large-12 columns">
          <div data-alert class="large-12 columns alert-box alert"><%= flash[:error] %><a href="#" class="close">&times;</a></div>
        </div>
      </div>
    <%- end %>

    <%- if flash[:notice] -%>
      <div class="row">
        <div class="large-12 columns">
          <div data-alert class="large-12 columns alert-box success"><%= flash[:notice] %><a href="#" class="close">&times;</a></div>
        </div>
      </div>
    <%- end %>

    <%- if flash[:alert] -%>
      <div class="row">
        <div class="large-12 columns">
          <div data-alert class="large-12 columns alert-box"><%= flash[:alert] %><a href="#" class="close">&times;</a></div>
        </div>
      </div>
    <%- end -%>

    <%= yield %>

    <script src="//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ['Open Sans:400italic,400,300,600,700']
        }
      });
    </script>

    <%= javascript_include_tag "application" %>
  </body>
</html>